export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_SUBJECT = 'GET_SUBJECT';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const SUBJECT_ERROR = 'SUBJECT_ERROR';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const ADD_SUBJECT = 'ADD_SUBJECT';

export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
