export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_SUBJECT = 'GET_SUBJECT';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const SUBJECT_ERROR = 'SUBJECT_ERROR';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const GET_MY_SUBJECTS = 'GET_MY_SUBJECTS';

export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';

export const LOGIN_SUCCESS_ADMIN = 'LOGIN_SUCCESS_ADMIN';
export const LOGIN_SUCCESS_TEACHER = 'LOGIN_SUCCESS_TEACHER';
export const LOGIN_SUCCESS_STUDENT = 'LOGIN_SUCESS_STUDENT';

export const GET_TEACHERS = 'GET_TEACHERS';
export const TEACHER_ERROR = 'TEACHER_ERROR';

export const GET_TEACHERS_REQUEST = 'GET_TEACHERS_REQUEST';
export const GET_TEACHERS_FAIL = 'GET_TEACHERS_FAIL';
export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS';
export const GET_TEACHERS_INIT = 'GET_TEACHERS_INIT';
export const CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT';

export const SUSPENDED_TEACHER_REQUEST = 'SUSPENDED_TEACHER_REQUEST';
export const SUSPENDED_TEACHER_SUCCESS = 'SUSPENDED_TEACHER_SUCCESS';
export const SUSPENDED_TEACHER_FAIL = 'SUSPENDED_TEACHER_FAIL';

export const APPROVE_APPOINTMENT_REQUEST = 'APPROVE_APPOINTMENT_REQUEST';
export const APPROVE_APPOINTMENT_SUCCESS = 'APPROVE_APPOINTMENT_SUCCESS';
export const APPROVE_APPOINTMENT_FAIL = 'APPROVE_APPOINTMENT_FAIL';
export const CANCEL_APPOINTMENT_REQUEST = 'CANCEL_APPOINTMENT_REQUEST';
export const CANCEL_APPOINTMENT_SUCCESS = 'CANCEL_APPOINTMENT_SUCCESS';
export const CANCEL_APPOINTMENT_FAIL = 'CANCEL_APPOINTMENT_FAIL';

export const SET_AVAILABLE_SUBJECT_REQUEST = 'SET_AVAILABLE_SUBJECT_REQUEST';
export const SET_AVAILABLE_SUBJECT_SUCCESS = 'SET_AVAILABLE_SUBJECT_SUCCESS';
export const SET_AVAILABLE_SUBJECT_FAIL = 'SET_AVAILABLE_SUBJECT_FAIL';
export const SET_NOT_AVAILABLE_SUBJECT_REQUEST =
  'SET_NOT_AVAILABLE_SUBJECT_REQUEST';
export const SET_NOT_AVAILABLE_SUBJECT_SUCCESS =
  'SET_NOT_AVAILABLE_SUBJECT_SUCCESS';
export const SET_NOT_AVAILABLE_SUBJECT_FAIL = 'SET_NOT_AVAILABLE_SUBJECT_FAIL';

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
export const GET_CATEGORY_INIT = 'GET_CATEGORY_INIT';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
